### ISSUE TITLE
Big initial memory overhead

### ISSUE THREAD

**Issue by fklemme** [bird-house/birdhousebuilder.recipe.tomcat#1]
With 512 MB _initial_ heap memory allocated, there is quite some memory given away which might not be used at all. See [catalina-wrapper.sh](https://github.com/bird-house/birdhousebuilder.recipe.tomcat/blob/master/birdhousebuilder/recipe/tomcat/catalina-wrapper.sh#L13):

```
NORMAL="-d64 -Xmx2048m -Xms512m -server"
```

Running a Phoenix server, this service seems to take up the most memory by far. Can we just strip the `Xms` parameter (or is it required)?

**Comment by fklemme** [comment]
A VM with 1 GB of RAM is hardly enough to run Phoenix without crashing. 36% of the memory is used up by tomcat; the one next to this is python with 5% memory usage.

![phoenix-1gb-vm](https://cloud.githubusercontent.com/assets/5053254/8422494/8729a5fe-1edc-11e5-8fca-71cf52112d28.png)

**Comment by cehbrecht** [comment]
i can make this configureable in the recipe ...

**Comment by cehbrecht** [comment]
`Xms`, `Xmx`, `MaxPermSize` are now configurable. Default values are much lower.

You can customize these values in malleefowl with `tomcat-xms`, `tomcat-xmx`, `tomcat-maxpermsize`.

**Comment by fklemme** [comment]
Nice, thanks a lot!

**Comment by fklemme** [comment]
Btw. Tomcat is still the biggest one with 240 MB memory consumption on startup - but that's okay, I guess.

I wonder what Tomcat is used for. Can you give me some insights @cehbrecht?

> /usr/bin/java -Djava.util.logging.config.file=/home/phoenix/.conda/envs/birdhouse/opt/apache-tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dtds.content.root.path=/home/phoenix/.conda/envs/birdhouse/var/lib/tomcat/content -Djava.awt.headless=true -d64 -Xmx1024m -Xms128m -server -XX:MaxPermSize=128m -Djava.endorsed.dirs=/home/phoenix/.conda/envs/birdhouse/opt/apache-tomcat/endorsed -classpath /home/phoenix/.conda/envs/birdhouse/opt/apache-tomcat/bin/bootstrap.jar:/home/phoenix/.conda/envs/birdhouse/opt/apache-tomcat/bin/tomcat-juli.jar -Dcatalina.base=/home/phoenix/.conda/envs/birdhouse/opt/apache-tomcat -Dcatalina.home=/home/phoenix/.conda/envs/birdhouse/opt/apache-tomcat -Djava.io.tmpdir=/home/phoenix/.conda/envs/birdhouse/opt/apache-tomcat/temp org.apache.catalina.startup.Bootstrap start

**Comment by cehbrecht** [comment]
tomcat is used for thredds only. Thredds has several service interfaces like "Web Mapping Service" which can be used to visualize netcdf files (including time axis).
